spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route-update_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/update_user

        - id: route-find_user_by_chat_id
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/find_user_by_chat_id

        - id: route-create_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/create_user

        - id: route-get_all_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_user

        - id: route-get_all_user_is_delete
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_user_is_delete

        - id: route-check_auth
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/check_auth
        #------------------------------------------------------------------------
        - id: route-get_all_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_schedule
        - id: route-get_all_free_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_free_schedule
        - id: route-add_free_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/add_free_schedule
        - id: route-add_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/add_schedule
    discovery:
      locator:
        enabled: true

  main:
    web-application-type: reactive

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

chat_id: ${CHAT_ID}
