spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route-get_courses_where_user_auth
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_courses_where_user_auth

        - id: route-get_title_theme_of_id
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_title_theme_of_id

        - id: route-delete_user_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/delete_user_in_course

        - id: route-delete_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/delete_course

        - id: route-add_question_in_theme
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/add_question_in_theme

        - id: route-delete_question
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/delete_question

        - id: route-update_question_in_theme
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/update_question_in_theme

        - id: route-get_all_question_of_theme
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_question_of_theme

        - id: route-delete_theme
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/delete_theme

        - id: route-check_auth_user_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/check_auth_user_in_course

        - id: route-change_auth_user_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/change_auth_user_in_course

        - id: route-update_theme_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/update_theme_in_course

        - id: route-add_user_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/add_user_in_course

        - id: route-add_theme_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/add_theme_in_course

        - id: route-update_title_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/update_title_course

        - id: route-add_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/add_course

        - id: route-get_all_users_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_users_in_course

        - id: route-get_all_themes_in_course
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_themes_in_course

        - id: route-get_all_courses
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_courses

        - id: route-update_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/update_user

        - id: route-find_user_by_chat_id
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/find_user_by_chat_id

        - id: route-create_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/create_user

        - id: route-get_all_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_user

        - id: route-get_all_user_is_delete
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/get_all_user_is_delete

        - id: route-check_auth
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/check_auth

        - id: route-find_users_fio_by_ids
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/find_users_fio_by_ids

        - id: route-find_themes_title_by_ids
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/find_themes_title_by_ids
        #------------------------------------------------------------------------

        - id: route-get_all_free_schedule_in_course
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_free_schedule_in_course

        - id: route-delete_user_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/delete_user_schedule

        - id: route-get_all_course_selected_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_course_selected_schedule

        - id: route-get_all_user_selected_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_user_selected_schedule

        - id: route-get_all_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_schedule

        - id: route-get_all_free_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_free_schedule

        - id: route-add_free_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/add_free_schedule

        - id: route-add_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/add_schedule

        - id: route-get_all_schedule_is_course
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/get_all_schedule_is_course

        - id: route-add_user_schedule
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/mini_app/add_user_schedule

    discovery:
      locator:
        enabled: true

  main:
    web-application-type: reactive

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

chat_id: ${CHAT_ID}
