spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route-save
          uri: http://api:8080
          predicates:
            - Path=/api/save
        - id: route-save_internal
          uri: http://internal:8081
          predicates:
            - Path=/api/save_internal
    discovery:
      locator:
        enabled: true

  main:
    web-application-type: reactive

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
