spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route-find_user_by_chat_id
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/find_user_by_chat_id

        - id: route-create_user
          uri: ${URI_API}
          predicates:
            - Path=/api/mini_app/create_user

        - id: route-save_internal
          uri: ${URI_INTERNAL}
          predicates:
            - Path=/api/save_internal
    discovery:
      locator:
        enabled: true

  main:
    web-application-type: reactive

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

chat_id: ${CHAT_ID}
